FROM python:3-alpine3.9
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /Merida
WORKDIR /Merida
RUN pip install -r requirements.txt
ENV INSTANCE_HOST 127.0.0.1
ENV DB_USER postgres
ENV DB_PASS <db password>
ENV DB_NAME merida-db
ENV DB_PORT 5432
EXPOSE 8080
CMD flask run

